### ISSUE TITLE
Dynamic README with contributors name

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/eth-unwrapped#2]
### Is your feature request related to a problem? Please describe
Contributors name no visible in readme

### Describe the solution you'd like
Modify the readme along with a github workflow to add contributors name and image in the readme automatically

**Comment by nwokporochukwuebuka** [comment]
Okay. I'd like to take this up @advaita-saha

**Comment by nwokporochukwuebuka** [comment]
I'm a GSSoC contributor and with my little knowledge in documentation and documentation tools like markdown, sphinx etc I believe I can do it. I'll send a proposal of how I intent to do this.

**Comment by advaita-saha** [comment]
@nwokporochukwuebuka sure go ahead

**Comment by nwokporochukwuebuka** [comment]
Here is my proposition:
### Contributors Name not visible in README.md


Here is my proposition:

### Contributors Name not visible in README.md

1. Create a markdown file named `CONTRIBUTOS.md` file. This file would contain the names and contributors image (optional)
2. Let it be arranged in a table format, for example

   | Name          | Image                           |
   | ------------- | ------------------------------- |
   | Advaita Saha  | ![Avaita Saha](link/to/image)   |
   | Bartick Maiti | ![Bartick Maiti](link/to/image) |

3. Create a Github workflow file in your projects directory to update the contributors `.github/workflows/update-contributors.yml`

4. Adding the following content to the workflow:

```
name: Update Contibutors

on:
    push:
        branches:
            - main
jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set Up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14

            - name: Install Dependencies
              run: npm install

            - name: Update Contributors
              run: node update-readme.js

            - name: Commit Changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add README.md
                git commit -m "Update contributors in README"
                git push
```

4. Create a `update-readme.js` file in the project's root directory and add the following code:

```
const fs = require('fs');

function updateMentor() {
    const contributorsContent = fs.readFileSync('CONTRIBUTORS.md', 'utf8');
    const readmeContent = fs.readFileSync('README.md', 'utf8');

    const updatedReadme = readmeContent.replace(
        /<!-- CONTRIBUTORS START -->(.|\n)*<!-- CONTRIBUTORS END -->/,
        `<!-- CONTRIBUTORS START -->\n\n${contributorsContent}\n<!-- CONTRIBUTORS END -->`
    );

    fs.writeFileSync('README.md', updatedReadme);
}

updateReadme();
```
5. Anytime the push event occurs on the main. The GitHub workflow will run
